const SEED_COMMENTS_KEY = 'lpsm_comments_seeded_v2'

const hciComments = (code, now) => [
  { id: `seed-1-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'Please update the references for ILO1 to include the latest edition.', courseOutcome: 'CO1', ilo: 'CO1-ILO1', coverageType: 'References', coverageDetail: 'The Design of Everyday Things', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-ref2-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'Please add more recent references for CO2-ILO1 regarding usability heuristics.', courseOutcome: 'CO2', ilo: 'CO2-ILO1', coverageType: 'References', coverageDetail: '10 Usability Heuristics for User Interface Design', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-ref3-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The WCAG references need updating to version 2.2 standards.', courseOutcome: 'CO3', ilo: 'CO3-ILO3', coverageType: 'References', coverageDetail: 'Web Content Accessibility Guidelines (WCAG) 2.2', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-ref4-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'The usability testing reference is appropriate but consider adding a supplementary text.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'References', coverageDetail: "Usability.gov: User Experience Basics", status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-2-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The accessibility topic needs more depth.', courseOutcome: 'CO3', ilo: 'CO3-ILO3', coverageType: 'Topic', coverageDetail: 'Accessibility & Ethics in AI', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-t2-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The cognitive foundations topic should include more on mental models.', courseOutcome: 'CO1', ilo: 'CO1-ILO1', coverageType: 'Topic', coverageDetail: 'Introduction to HCI & Cognitive Foundations', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-t3-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'Low-fidelity prototyping topic should cover paper prototyping more thoroughly.', courseOutcome: 'CO2', ilo: 'CO2-ILO2', coverageType: 'Topic', coverageDetail: 'Low-Fidelity Prototyping', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-4-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'The usability testing plan is comprehensive but needs more detail on the metrics section.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'Topic', coverageDetail: 'Usability Testing', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-t5-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'High-fidelity prototyping should also cover design system fundamentals.', courseOutcome: 'CO3', ilo: 'CO3-ILO1', coverageType: 'Topic', coverageDetail: 'High-Fidelity Prototyping', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-3-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'Industry standard practice now uses 3-factor auth for this topic. Please update the TLA to cover this.', courseOutcome: 'CO2', ilo: 'CO2-ILO2', coverageType: 'TLA', coverageDetail: 'UI Component Audit', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-tla2-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The card sorting TLA is good but needs a debrief component.', courseOutcome: 'CO1', ilo: 'CO1-ILO3', coverageType: 'TLA', coverageDetail: 'Card Sorting Exercise', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-tla3-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'Please add a usability testing TLA where students conduct actual user tests.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'TLA', coverageDetail: 'Usability Test Session', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-tla4-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The persona workshop should include time for user research synthesis.', courseOutcome: 'CO1', ilo: 'CO1-ILO2', coverageType: 'TLA', coverageDetail: 'Persona Workshop', status: 'pending', resolved: false, suggestedRefs: [] },
]

const seComments = (code, now) => [
  { id: `seed-se1-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'Please ensure the references include the latest IEEE software engineering standards.', courseOutcome: 'CO1', ilo: 'CO1-ILO1', coverageType: 'References', coverageDetail: 'SWEBOK Guide v4', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se2-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The requirements engineering section needs a supplementary reading on Agile requirements.', courseOutcome: 'CO2', ilo: 'CO2-ILO1', coverageType: 'References', coverageDetail: 'Agile Estimating and Planning', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se3-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The testing strategy should include references to continuous integration practices.', courseOutcome: 'CO3', ilo: 'CO3-ILO2', coverageType: 'References', coverageDetail: 'CI/CD Best Practices', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se4-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'The software design patterns coverage is appropriate but could include more modern architectural patterns.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'References', coverageDetail: 'Clean Architecture', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se5-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The software process model topic should cover the Spiral model in more depth.', courseOutcome: 'CO1', ilo: 'CO1-ILO1', coverageType: 'Topic', coverageDetail: 'Software Process Models', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se6-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'Add more depth to the requirements elicitation topic with real-world case studies.', courseOutcome: 'CO2', ilo: 'CO2-ILO1', coverageType: 'Topic', coverageDetail: 'Requirements Elicitation', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se7-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The unit testing topic should include a practical exercise with test-driven development.', courseOutcome: 'CO3', ilo: 'CO3-ILO1', coverageType: 'Topic', coverageDetail: 'Unit Testing Fundamentals', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se8-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'The software maintenance topic should include legacy system migration patterns.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'Topic', coverageDetail: 'Software Maintenance & Evolution', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se9-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The code review TLA should include a formal inspection process component.', courseOutcome: 'CO3', ilo: 'CO3-ILO2', coverageType: 'TLA', coverageDetail: 'Code Review & Inspection', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se10-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The requirements workshop TLA should incorporate stakeholder interview practice.', courseOutcome: 'CO2', ilo: 'CO2-ILO2', coverageType: 'TLA', coverageDetail: 'Requirements Workshop', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se11-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s3-${now.getTime()}`, submissionLabel: 'Review 3', submittedAt: new Date(now - 21600000).toISOString(), createdAt: new Date(now - 21600000).toISOString(), reviewer: 'DANILA, JUNAR', role: 'Program Head', recipientRole: 'instructor', components: {}, comment: 'The software quality assurance TLA should align with ISO 25010 standards.', courseOutcome: 'CO4', ilo: 'CO4-ILO1', coverageType: 'TLA', coverageDetail: 'Software Quality Assurance Plan', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se12-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s1-${now.getTime()}`, submissionLabel: 'Review 1', submittedAt: new Date(now - 86400000).toISOString(), createdAt: new Date(now - 86400000).toISOString(), reviewer: 'SANTOS, MARIA', role: 'Director of Libraries', recipientRole: 'instructor', components: {}, comment: 'The project management topic should include risk management and mitigation strategies.', courseOutcome: 'CO1', ilo: 'CO1-ILO2', coverageType: 'Topic', coverageDetail: 'Project Planning & Risk Management', status: 'pending', resolved: false, suggestedRefs: [] },
  { id: `seed-se13-${now.getTime()}`, courseCode: code, section: 'Course Coverage', submissionId: `seed-s2-${now.getTime()}`, submissionLabel: 'Review 2', submittedAt: new Date(now - 43200000).toISOString(), createdAt: new Date(now - 43200000).toISOString(), reviewer: 'CRUZ, ROBERTO', role: 'Industry Consultant', recipientRole: 'instructor', components: {}, comment: 'The architecture design TLA should include hands-on experience with UML modeling tools.', courseOutcome: 'CO3', ilo: 'CO3-ILO1', coverageType: 'TLA', coverageDetail: 'UML Architecture Modeling', status: 'pending', resolved: false, suggestedRefs: [] },
]

const courseCommentMap = {
  BIT313L: hciComments,
  BIT313: hciComments,
  BSCS322L: seComments,
  BSCS322: seComments,
}

export function seedDummyComments(code) {
  if (!code) return
  try {
    const seeded = localStorage.getItem(SEED_COMMENTS_KEY)
    if (seeded) return
    const existing = JSON.parse(localStorage.getItem('approval_comments_v1') || '[]')
    const now = new Date()
    const gen = courseCommentMap[code] || hciComments
    const merged = [...gen(code, now), ...existing]
    localStorage.setItem('approval_comments_v1', JSON.stringify(merged))
    localStorage.setItem(SEED_COMMENTS_KEY, '1')
    if (import.meta.env.DEV) console.log('Seeded dummy comments for', code)
  } catch (e) {
    console.error('Failed to seed comments', e)
  }
}
